server:
  port: 9700
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat_db
    username: postgres
    password: daon!@34
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
  devtools:
    livereload:
      enabled: true

  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp